#ifndef OCVCOIN_CHAINPARAMSSEEDS_H
#define OCVCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the ocvcoin network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 */
static const uint8_t chainparams_seed_main[] = {
    0x01,0x04,0x00,0x00,0x00,0x00,0x20,0x8d,
};

static const uint8_t chainparams_seed_test[] = {
    0x01,0x04,0x00,0x00,0x00,0x00,0x20,0x8d,
};
#endif // OCVCOIN_CHAINPARAMSSEEDS_H